from src.common import *


ENEMIES = {
    "zako": {
        "health": 1,
        "sprite": Sprite(48, 0),
        "shoot_cd": 0,
        "emitter": "",
        "score": 10,
        "xspeed": 1,
        "yspeed": 0,
        "can_approach": True,
        "bonus_chance": 10,
    },
    "shield": {
        "health": 2,
        "sprite": Sprite(32, 0),
        "shoot_cd": 0,
        "emitter": "",
        "score": 20,
        "xspeed": 1,
        "yspeed": 0,
        "can_approach": True,
        "bonus_chance": 25,
    },
    "shooter": {
        "health": 1,
        "sprite": Sprite(16, 0),
        "shoot_cd": 120,
        "emitter": "single",
        "score": 20,
        "xspeed": 1,
        "yspeed": 0,
        "can_approach": True,
        "bonus_chance": 25,
    },
    "shooter2": {
        "health": 2,
        "sprite": Sprite(32, 0),
        "shoot_cd": 60,
        "emitter": "double",
        "score": 30,
        "xspeed": 1,
        "yspeed": 0,
        "can_approach": False,
        "bonus_chance": 30,
    },
    "fast": {
        "health": 1,
        "sprite": Sprite(64, 0),
        "shoot_cd": 0,
        "emitter": "",
        "score": 15,
        "xspeed": 2,
        "yspeed": 0,
        "can_approach": True,
        "bonus_chance": 25,
    },
    "diver": {
        "health": 1,
        "sprite": Sprite(64, 16),
        "shoot_cd": 0,
        "emitter": "",
        "score": 15,
        "xspeed": 1,
        "yspeed": 1,
        "can_approach": False,
        "bonus_chance": 25,
    },
    "boss": {
        "health": 15,
        "sprite": Sprite(0, 16),
        "shoot_cd": 50,
        "emitter": "single",
        "score": 500,
        "xspeed": 1,
        "yspeed": 0,
        "can_approach": False,
        "bonus_chance": 100,
    },
}
